### ISSUE TITLE
Crash after unlocking the lock-screen

### ISSUE THREAD

**Issue by sojusnik** [leonardo-bartoli/gnome-shell-extension-Recents#5] opened 2017-03-03 21:19 UTC
On Ubuntu Gnome 16.10 the Gnome-Shell is sporadically crashing after unlocking the lock-screen. Restarting it (Alt+F2, then r) helps, but gets annoying over time. It seems, that your extension is causing this. Look out for "JS ERROR".

The last crash happened around 20:53:21 - 35, the appropriate log is to be found here https://paste.gnome.org/pugtmmdnr (copied from journalctl) and https://paste.gnome.org/psxx0kqme (taken from /var/log/syslog).

Thanks for helping!

**Comment by leonardo-bartoli** [comment] 2017-03-27 09:11
Hi sorry for the late replay.
I was not able to reproduce your problem, I tried to change how the settings are handled by the extension, can you please try this one 241f5d550ee176c7f2900cab1c251c63c0415edc to see if there are any improvements?

**Comment by sojusnik** [comment] 2017-04-12 17:34
When your extension is deactivated, Gnome is crashing less often, but still is. Can you have a look on the above mentioned log and express your opinion?

Since I'm not familiar with git, I would prefer to install the updated version from Gnome's extension site and give you feedback.

**Comment by leonardo-bartoli** [comment] 2017-04-18 21:40
Looks like a problem with gnome-settings, I'm going to release a new version on e.g.o in a couple of days.

**Comment by leonardo-bartoli** [comment] 2017-09-07 21:28
Closing this bug, should be fixed with the current release

**Closed as completed by leonardo-bartoli** 2017-09-07 21:28 UTC
